name: figma-plugin

on:
  push:
    branches: [main]
    paths:
      - "apps/figma-plugin/**"

  pull_request:
    branches: [main]
    paths:
      - "apps/figma-plugin/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.25.1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "pnpm"

      - run: pnpm i
      - run: pnpm build:figma-plugin:production

      - uses: actions/upload-artifact@v2
        with:
          name: figma-plugin
          path: apps/figma-plugin/dist/production
