name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.25.1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "pnpm"
      - run: pnpm i
      - run: pnpm lint
